Implement `__fspath__` for `ResourcePath` instances
google/etils pull request #28
Opened 2022-01-06 05:35 UTC by joshiayush

`zipfile.Path` and `zipp.Path` both implements `__str__` method to return a string representation of the `Path` instance which we can probably use here in `ResourcePath`

Signed-off-by: Ayush Joshi <ayush854032@gmail.com>

2022-01-06 18:38 UTC, Conchylicultor requested changes
Thanks for the PR. Unfortunately, it's more complicated than that.

The `__fspath__` is defined in https://www.python.org/dev/peps/pep-0519/ to allow compatibility with the rest of the python ecosystem:

```python
p = epath.resource_path('my_module') / 'some/subfolder.json'

with open(p) as f:
  print(f.read())
```

This will work when running with `python main.py` (`p` is a `etils.Path`).
However, when running inside a [zipapp](https://docs.python.org/3/library/zipapp.html) (`python main.pyz`), `p` will be a `zipfile.Path`. This will fail because `open` cannot decode the file inside the `.zip`.

The solution is to have `os.fspath(zipfile.Path())` to extract the file in a `tmpfile` and return the `/tmp/` location.

2022-01-07 01:34 UTC, joshiayush commented
@Conchylicultor If I'm not wrong then the extracted files should be saved inside the root `/tmp/` directory but this is on `linux`, what about windows? what about `C:\WINDOWS\Temp` on windows?

How will we do the cleaning? Should I create a destructor that will clean up the temporary extracted files once the object is dead? I'll check if the extraction happened on the object or not.

2022-01-07 10:50 UTC, Conchylicultor commented
> @Conchylicultor If I'm not wrong then the extracted files should be saved inside the root /tmp/ directory but this is on linux, what about windows? what about C:\WINDOWS\Temp on windows?

We would use https://docs.python.org/3/library/tempfile.html to get a unique tmp path.

I don't think the size is a big issue. `resource_path` is used for resource files stored along the `my_modules.py`, so so files are very small (< MB in the most extreme case).

I think at first, we could even let the OS auto-clear those files. If this is an issue, we can just register a 
https://docs.python.org/3/library/atexit.html#atexit.register

Ideally, we should have a global cache though to avoid extracting those files multiple time.

2022-01-08 15:45 UTC, joshiayush commented
@Conchylicultor Hey sorry I did not have time to look at this. I think when you first said this I didn't understand it properly might be because of my lack of experience with [zipapp](https://docs.python.org/3/library/zipapp.html).

> Thanks for the PR. Unfortunately, it's more complicated than that.
> 
> The `__fspath__` is defined in https://www.python.org/dev/peps/pep-0519/ to allow compatibility with the rest of the python ecosystem:
> 
> ```python
> p = epath.resource_path('my_module') / 'some/subfolder.json'
> 
> with open(p) as f:
>   print(f.read())
> ```
> 
> This will work when running with `python main.py` (`p` is a `etils.Path`). However, when running inside a [zipapp](https://docs.python.org/3/library/zipapp.html) (`python main.pyz`), `p` will be a `zipfile.Path`. This will fail because `open` cannot decode the file inside the `.zip`.
> 
> The solution is to have `os.fspath(zipfile.Path())` to extract the file in a `tmpfile` and return the `/tmp/` location.

Or might be because of the example you gave because with my knowledge and after tons of googling it's really hard to believe that you can actually join a path like that with an archive. It could be because of my limited knowledge but the only way I know to access a nested file inside of an archive is to have a path of the root archive beforehand.

```python
p = epath.resource_path('my_module') / 'some/subfolder.json'

with open(p) as f:
  print(f.read())
```

I've debugged the `resource_path()` function properly in order to understand its working and when I try to join a path like that in above example with an archive I get an `AttributeError` and I don't think that I need to post the traceback here because the problem is with my understanding because of which I'm providing wrong instances to wrong functions which results in that exception.

I'm still open to implement that function but if you think that it's something that will be complicated for me to implement then either you can close this PR :) or give me some direction. If you close this PR I'll go look at some other aspect of this library and see what I can work on, what do you say?

2022-01-10 13:21 UTC, Conchylicultor commented
I'm not sure I understand. Where are you getting a `AttributeError` ?

```python
p = epath.resource_path('my_module')
```
returns a `pathlib`-like object, which support joining path as `p / 'sub_folder'`.

When running inside a `.zip` file, it would return a `zipfile.Path` object: https://docs.python.org/3/library/zipfile.html#path-objects which support joining other path: https://docs.python.org/3/library/zipfile.html#zipfile.Path.joinpath

> I'm still open to implementing that function but if you think that it's something that will be complicated for me to implement then either you can close this PR :) or give me some direction. If you close this PR I'll go look at some other aspect of this library and see what I can work on, what do you say?

I think this PR can be closed. While we don't have a concrete need for this feature, it might not be worth spending time on it.

2022-01-11 01:47 UTC, closed without merging